ARG JAVA_VERSION=21

FROM eclipse-temurin:${JAVA_VERSION}-jre
WORKDIR /app

RUN addgroup --system spring && adduser --system --ingroup spring spring

COPY app.jar /app/app.jar

RUN mkdir -p /app/uploads/images && chown -R spring:spring /app/uploads

USER spring
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
