name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build --no-daemon
        env:
          APP_PORT: ${{ secrets.APP_PORT }}
          JAVA_VERSION: ${{ secrets.JAVA_VERSION }}
          SPRING_PROFILES_ACTIVE: ${{ secrets.SPRING_PROFILES_ACTIVE }}
          SPRING_JPA_HIBERNATE_DDL_AUTO: ${{ secrets.SPRING_JPA_HIBERNATE_DDL_AUTO }}

          ORACLE_PORT: ${{ secrets.ORACLE_PORT }}
          ORACLE_PASSWORD: ${{ secrets.ORACLE_PASSWORD }}
          ORACLE_APP_USER: ${{ secrets.ORACLE_APP_USER }}
          ORACLE_APP_PASSWORD: ${{ secrets.ORACLE_APP_PASSWORD }}

          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
